// REDUX ACTION TYPES
// export const TICK = 'TICK'
// export const INCREMENT = 'INCREMENT'
// export const DECREMENT = 'DECREMENT'
// export const RESET = 'RESET'
export const USER_DETAILS='USER_DETAILS'
export const USER_TOKEN='USER_TOKEN'
export const CART_PRODUCTS='CART_PRODUCTS'
export const PRODUCT_LISTS='PRODUCT_LISTS'
export const CHOOSE_MEDICINE='CHOOSE_MEDICINE'
export const UPLOAD_PRESCRIPTION='UPLOAD_PRESCRIPTION'


